### ISSUE TITLE
Logo not visible in navbar

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth.github.io#11]
![image](https://user-images.githubusercontent.com/14032427/108403259-89ca2100-7244-11eb-8d07-3002d3a67a35.png)

it should become visible as soon as when we scroll down from first component. 

steps:
1. open webpage
2. scroll to bottom
3. refresh
4. scroll to top
5. now scroll down. the logo does not become visible.

**Comment by Abhijay007** [comment]
@YashKumarVerma sir can I work on this?
