### ISSUE TITLE
Privacy Feature card not animated

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth.github.io#12]
The privacy tab does not flip when user reaches

![image](https://user-images.githubusercontent.com/14032427/108404007-5b991100-7245-11eb-9357-6e4996576f2b.png)

**Comment by Abhijay007** [comment]
@YashKumarVerma sir can I work on this?

**Comment by YashKumarVerma** [comment]
Sure. Please send a PR for the previous issue, then i can assign you on this one.

**Comment by Abhijay007** [comment]
> Sure. Please send a PR for the previous issue, then i can assign you on this one.

already did sir 👍
