### ISSUE TITLE
Excess margin on left side

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth.github.io#13]
the margin on the left side of customer section is much more than required.

Make it as similar to the developer section.

![image](https://user-images.githubusercontent.com/14032427/108404485-ef6add00-7245-11eb-9fda-455d30138784.png)

should be equal to
![image](https://user-images.githubusercontent.com/14032427/108404522-fbef3580-7245-11eb-973d-6c05a2a0be90.png)

**Comment by YashKumarVerma** [comment]
![Uploading image.png…]()

**Comment by Abhijay007** [comment]
@YashKumarVerma sir can I work on this?

**Comment by YashKumarVerma** [comment]
Sure. Please send a PR for the previous issue, then i can assign you on this one.

**Comment by m-code12** [comment]
@YashKumarVerma I would like to work on this.Can you assign me this issue?

**Comment by Abhijay007** [comment]
but I already solved it 😅 

![margin-left](https://user-images.githubusercontent.com/64387054/108417064-868b6100-7255-11eb-80f0-316aebc61627.PNG)

but as @YashKumarVerma assign this to you @m-code12 you can work on it. 
No problem 👍
