### ISSUE TITLE
Add Twitter account on footer

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth.github.io#16]
Please add https://twitter.com/UniAuth to the site footer with a suitable icon.

**Comment by Abhijay007** [comment]
I want to work on this

**Comment by Abhijay007** [comment]
@YashKumarVerma I have a suggestion can I introduce micro animations to the icons like this:

![twitter-micro](https://user-images.githubusercontent.com/64387054/108461829-77ca9b80-72a1-11eb-8f39-a20d28f79c3c.gif)

**Comment by Abhijay007** [comment]
I can do the same for the Github icon

**Comment by YashKumarVerma** [comment]
For this issue, just include the Twitter icon. 

And open a new issue for adding the animations

**Comment by Abhijay007** [comment]
> For this issue, just include the Twitter icon.
> 
> And open a new issue for adding the animations

ok
