### ISSUE TITLE
Display tweet feed on site

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth.github.io#17]
Display tweets from our twitter handle(https://twitter.com/UniAuth) on the website as a widget.

**Comment by Abhijay007** [comment]
I want to work on this

**Comment by Abhijay007** [comment]
can I work on this now I am done with the PR of the previous issue?

**Comment by m-code12** [comment]
@YashKumarVerma I would like to work on this issue.

**Comment by Abhijay007** [comment]
> @YashKumarVerma I would like to work on this issue.

I @m-code12  am already working on this

**Comment by YashKumarVerma** [comment]
Don't worry, we'll readily add new issues.

There are frontend issues in the `uniauth-backend` repo as well.

**Comment by Abhijay007** [comment]
@YashKumarVerma where on the site you want this to implement means on which part 
the above footer or in middle somewhere?

**Comment by Abhijay007** [comment]
@YashKumarVerma but UniAuth Twitter handle doesn't have any tweets 😅 
can you please tweet something for testing 😄?

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma but UniAuth Twitter handle doesn't have any tweets 😅
> can you please tweet something for testing 😄?

alright, XD
